# Generated by Django 4.2 on 2023-04-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_like_likedprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='like',
        ),
    ]
