# Generated by Django 4.2 on 2023-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_remove_tag_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like',
        ),
    ]
