# Generated by Django 4.2 on 2023-05-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0007_answer_rating_likeanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeanswer',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='user',
            new_name='profile',
        ),
    ]
