# Generated by Django 4.2 on 2023-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_rename_user_likeanswer_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeanswer',
            name='rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='rate',
            field=models.BooleanField(default=True),
        ),
    ]
