# Generated by Django 4.2 on 2023-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0009_likeanswer_rate_likequestion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='rate',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='rate',
            field=models.BooleanField(),
        ),
    ]
